# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26a336ec5886afe13c4db3b534fa1af0d581203bf3ebff6c69eba9bdbc8b22c8f53deebd45a4353fe13a283ab06d0f4ea612947830ffca71ea5569455b860de2

test:
  secret_key_base: f6de4048dd8b2f7ec2f9bdaa29481094a1c63932b5af620925106eaa6c9c828ffd0175ae6daf2fe89910b787d4666a8c4e0813c794067f046d3426730ba27175

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
